select 'ORGANICO' as 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then organicimpressions else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then organicimpressions else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then organicimpressions else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then organicimpressions else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then organicimpressions else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then organicimpressions else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then organicimpressions else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then organicimpressions else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then organicimpressions else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then organicimpressions else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then organicimpressions else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then organicimpressions else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then organicimpressions else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then organicimpressions else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then organicimpressions else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then organicimpressions else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then organicimpressions else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then organicimpressions else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then organicimpressions else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then organicimpressions else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then organicimpressions else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then organicimpressions else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then organicimpressions else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then organicimpressions else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then organicimpressions else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then organicimpressions else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then organicimpressions else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then organicimpressions else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then organicimpressions else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then organicimpressions else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then organicimpressions else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year% 
union 
select 'PAGO' as 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then paidimpressions else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then paidimpressions else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then paidimpressions else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then paidimpressions else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then paidimpressions else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then paidimpressions else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then paidimpressions else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then paidimpressions else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then paidimpressions else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then paidimpressions else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then paidimpressions else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then paidimpressions else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then paidimpressions else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then paidimpressions else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then paidimpressions else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then paidimpressions else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then paidimpressions else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then paidimpressions else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then paidimpressions else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then paidimpressions else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then paidimpressions else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then paidimpressions else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then paidimpressions else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then paidimpressions else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then paidimpressions else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then paidimpressions else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then paidimpressions else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then paidimpressions else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then paidimpressions else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then paidimpressions else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then paidimpressions else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year% 
union 
select 'TOTAL' as 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then totalimpressions else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then totalimpressions else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then totalimpressions else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then totalimpressions else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then totalimpressions else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then totalimpressions else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then totalimpressions else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then totalimpressions else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then totalimpressions else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then totalimpressions else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then totalimpressions else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then totalimpressions else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then totalimpressions else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then totalimpressions else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then totalimpressions else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then totalimpressions else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then totalimpressions else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then totalimpressions else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then totalimpressions else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then totalimpressions else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then totalimpressions else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then totalimpressions else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then totalimpressions else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then totalimpressions else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then totalimpressions else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then totalimpressions else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then totalimpressions else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then totalimpressions else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then totalimpressions else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then totalimpressions else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then totalimpressions else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year%