select 'GUSTA' AS 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then likes else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then likes else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then likes else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then likes else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then likes else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then likes else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then likes else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then likes else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then likes else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then likes else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then likes else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then likes else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then likes else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then likes else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then likes else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then likes else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then likes else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then likes else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then likes else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then likes else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then likes else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then likes else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then likes else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then likes else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then likes else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then likes else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then likes else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then likes else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then likes else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then likes else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then likes else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year%
union 
select 'COMENTARIOS' AS 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then comments else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then comments else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then comments else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then comments else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then comments else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then comments else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then comments else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then comments else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then comments else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then comments else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then comments else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then comments else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then comments else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then comments else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then comments else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then comments else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then comments else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then comments else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then comments else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then comments else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then comments else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then comments else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then comments else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then comments else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then comments else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then comments else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then comments else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then comments else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then comments else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then comments else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then comments else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year%
union 
select 'COMPARTIDOS' AS 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then shares else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then shares else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then shares else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then shares else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then shares else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then shares else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then shares else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then shares else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then shares else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then shares else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then shares else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then shares else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then shares else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then shares else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then shares else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then shares else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then shares else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then shares else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then shares else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then shares else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then shares else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then shares else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then shares else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then shares else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then shares else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then shares else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then shares else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then shares else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then shares else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then shares else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then shares else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year%
union 
select 'CLICKS' AS 'TIPO', 
sum(case when substring(ctimestamp, 7, 2)=01 then clicks else 0 end) as '01', 
sum(case when substring(ctimestamp, 7, 2)=02 then clicks else 0 end) as '02', 
sum(case when substring(ctimestamp, 7, 2)=03 then clicks else 0 end) as '03', 
sum(case when substring(ctimestamp, 7, 2)=04 then clicks else 0 end) as '04', 
sum(case when substring(ctimestamp, 7, 2)=05 then clicks else 0 end) as '05', 
sum(case when substring(ctimestamp, 7, 2)=06 then clicks else 0 end) as '06', 
sum(case when substring(ctimestamp, 7, 2)=07 then clicks else 0 end) as '07', 
sum(case when substring(ctimestamp, 7, 2)=08 then clicks else 0 end) as '08', 
sum(case when substring(ctimestamp, 7, 2)=09 then clicks else 0 end) as '09', 
sum(case when substring(ctimestamp, 7, 2)=10 then clicks else 0 end) as '10', 
sum(case when substring(ctimestamp, 7, 2)=11 then clicks else 0 end) as '11', 
sum(case when substring(ctimestamp, 7, 2)=12 then clicks else 0 end) as '12', 
sum(case when substring(ctimestamp, 7, 2)=13 then clicks else 0 end) as '13', 
sum(case when substring(ctimestamp, 7, 2)=14 then clicks else 0 end) as '14', 
sum(case when substring(ctimestamp, 7, 2)=15 then clicks else 0 end) as '15', 
sum(case when substring(ctimestamp, 7, 2)=16 then clicks else 0 end) as '16', 
sum(case when substring(ctimestamp, 7, 2)=17 then clicks else 0 end) as '17', 
sum(case when substring(ctimestamp, 7, 2)=18 then clicks else 0 end) as '18', 
sum(case when substring(ctimestamp, 7, 2)=19 then clicks else 0 end) as '19', 
sum(case when substring(ctimestamp, 7, 2)=20 then clicks else 0 end) as '20', 
sum(case when substring(ctimestamp, 7, 2)=21 then clicks else 0 end) as '21', 
sum(case when substring(ctimestamp, 7, 2)=22 then clicks else 0 end) as '22', 
sum(case when substring(ctimestamp, 7, 2)=23 then clicks else 0 end) as '23', 
sum(case when substring(ctimestamp, 7, 2)=24 then clicks else 0 end) as '24', 
sum(case when substring(ctimestamp, 7, 2)=25 then clicks else 0 end) as '25', 
sum(case when substring(ctimestamp, 7, 2)=26 then clicks else 0 end) as '26', 
sum(case when substring(ctimestamp, 7, 2)=27 then clicks else 0 end) as '27', 
sum(case when substring(ctimestamp, 7, 2)=28 then clicks else 0 end) as '28', 
sum(case when substring(ctimestamp, 7, 2)=29 then clicks else 0 end) as '29', 
sum(case when substring(ctimestamp, 7, 2)=30 then clicks else 0 end) as '30', 
sum(case when substring(ctimestamp, 7, 2)=31 then clicks else 0 end) as '31' 
from actividad.aralleida_fbposts 
where substring(ctimestamp, 5, 2)=%actual_month% AND substring(ctimestamp, 1, 4)=%actual_year%