select 'altas', 
sum(case when substring(fecha,9,2)=01 then Nuevos_Me_gusta_Diario else 0 end) as '01', 
sum(case when substring(fecha,9,2)=02 then Nuevos_Me_gusta_Diario else 0 end) as '02', 
sum(case when substring(fecha,9,2)=03 then Nuevos_Me_gusta_Diario else 0 end) as '03', 
sum(case when substring(fecha,9,2)=04 then Nuevos_Me_gusta_Diario else 0 end) as '04', 
sum(case when substring(fecha,9,2)=05 then Nuevos_Me_gusta_Diario else 0 end) as '05', 
sum(case when substring(fecha,9,2)=06 then Nuevos_Me_gusta_Diario else 0 end) as '06', 
sum(case when substring(fecha,9,2)=07 then Nuevos_Me_gusta_Diario else 0 end) as '07', 
sum(case when substring(fecha,9,2)=08 then Nuevos_Me_gusta_Diario else 0 end) as '08', 
sum(case when substring(fecha,9,2)=09 then Nuevos_Me_gusta_Diario else 0 end) as '09', 
sum(case when substring(fecha,9,2)=10 then Nuevos_Me_gusta_Diario else 0 end) as '10', 
sum(case when substring(fecha,9,2)=11 then Nuevos_Me_gusta_Diario else 0 end) as '11', 
sum(case when substring(fecha,9,2)=12 then Nuevos_Me_gusta_Diario else 0 end) as '12', 
sum(case when substring(fecha,9,2)=13 then Nuevos_Me_gusta_Diario else 0 end) as '13', 
sum(case when substring(fecha,9,2)=14 then Nuevos_Me_gusta_Diario else 0 end) as '14', 
sum(case when substring(fecha,9,2)=15 then Nuevos_Me_gusta_Diario else 0 end) as '15', 
sum(case when substring(fecha,9,2)=16 then Nuevos_Me_gusta_Diario else 0 end) as '16', 
sum(case when substring(fecha,9,2)=17 then Nuevos_Me_gusta_Diario else 0 end) as '17', 
sum(case when substring(fecha,9,2)=18 then Nuevos_Me_gusta_Diario else 0 end) as '18', 
sum(case when substring(fecha,9,2)=19 then Nuevos_Me_gusta_Diario else 0 end) as '19', 
sum(case when substring(fecha,9,2)=20 then Nuevos_Me_gusta_Diario else 0 end) as '20', 
sum(case when substring(fecha,9,2)=21 then Nuevos_Me_gusta_Diario else 0 end) as '21', 
sum(case when substring(fecha,9,2)=22 then Nuevos_Me_gusta_Diario else 0 end) as '22', 
sum(case when substring(fecha,9,2)=23 then Nuevos_Me_gusta_Diario else 0 end) as '23', 
sum(case when substring(fecha,9,2)=24 then Nuevos_Me_gusta_Diario else 0 end) as '24', 
sum(case when substring(fecha,9,2)=25 then Nuevos_Me_gusta_Diario else 0 end) as '25', 
sum(case when substring(fecha,9,2)=26 then Nuevos_Me_gusta_Diario else 0 end) as '26', 
sum(case when substring(fecha,9,2)=27 then Nuevos_Me_gusta_Diario else 0 end) as '27', 
sum(case when substring(fecha,9,2)=28 then Nuevos_Me_gusta_Diario else 0 end) as '28', 
sum(case when substring(fecha,9,2)=29 then Nuevos_Me_gusta_Diario else 0 end) as '29', 
sum(case when substring(fecha,9,2)=30 then Nuevos_Me_gusta_Diario else 0 end) as '30', 
sum(case when substring(fecha,9,2)=31 then Nuevos_Me_gusta_Diario else 0 end) as '31' 
from actividad.aralleida_fb_stats 
where substring(fecha,6,2)=%actual_month% AND substring(fecha,1,4)=%actual_year%
union 
select 'bajas', 
sum(case when substring(fecha,9,2)=01 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '01', 
sum(case when substring(fecha,9,2)=02 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '02', 
sum(case when substring(fecha,9,2)=03 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '03', 
sum(case when substring(fecha,9,2)=04 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '04', 
sum(case when substring(fecha,9,2)=05 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '05', 
sum(case when substring(fecha,9,2)=06 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '06', 
sum(case when substring(fecha,9,2)=07 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '07', 
sum(case when substring(fecha,9,2)=08 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '08', 
sum(case when substring(fecha,9,2)=09 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '09', 
sum(case when substring(fecha,9,2)=10 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '10', 
sum(case when substring(fecha,9,2)=11 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '11', 
sum(case when substring(fecha,9,2)=12 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '12', 
sum(case when substring(fecha,9,2)=13 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '13', 
sum(case when substring(fecha,9,2)=14 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '14', 
sum(case when substring(fecha,9,2)=15 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '15', 
sum(case when substring(fecha,9,2)=16 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '16', 
sum(case when substring(fecha,9,2)=17 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '17', 
sum(case when substring(fecha,9,2)=18 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '18', 
sum(case when substring(fecha,9,2)=19 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '19', 
sum(case when substring(fecha,9,2)=20 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '20', 
sum(case when substring(fecha,9,2)=21 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '21', 
sum(case when substring(fecha,9,2)=22 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '22', 
sum(case when substring(fecha,9,2)=23 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '23', 
sum(case when substring(fecha,9,2)=24 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '24', 
sum(case when substring(fecha,9,2)=25 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '25', 
sum(case when substring(fecha,9,2)=26 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '26', 
sum(case when substring(fecha,9,2)=27 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '27', 
sum(case when substring(fecha,9,2)=28 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '28', 
sum(case when substring(fecha,9,2)=29 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '29', 
sum(case when substring(fecha,9,2)=30 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '30', 
sum(case when substring(fecha,9,2)=31 then (Ya_no_me_gusta_Diario)*-1 else 0 end) as '31' 
from actividad.aralleida_fb_stats
where substring(fecha,6,2)=%actual_month% AND substring(fecha,1,4)=%actual_year%