select CONCAT('RT') as interacciones, 
sum(case when substring(tiempo,9,2)=01 then RT else 0 end) as '01', 
sum(case when substring(tiempo,9,2)=02 then RT else 0 end) as '02', 
sum(case when substring(tiempo,9,2)=03 then RT else 0 end) as '03', 
sum(case when substring(tiempo,9,2)=04 then RT else 0 end) as '04', 
sum(case when substring(tiempo,9,2)=05 then RT else 0 end) as '05', 
sum(case when substring(tiempo,9,2)=06 then RT else 0 end) as '06', 
sum(case when substring(tiempo,9,2)=07 then RT else 0 end) as '07', 
sum(case when substring(tiempo,9,2)=08 then RT else 0 end) as '08', 
sum(case when substring(tiempo,9,2)=09 then RT else 0 end) as '09', 
sum(case when substring(tiempo,9,2)=10 then RT else 0 end) as '10', 
sum(case when substring(tiempo,9,2)=11 then RT else 0 end) as '11', 
sum(case when substring(tiempo,9,2)=12 then RT else 0 end) as '12', 
sum(case when substring(tiempo,9,2)=13 then RT else 0 end) as '13', 
sum(case when substring(tiempo,9,2)=14 then RT else 0 end) as '14', 
sum(case when substring(tiempo,9,2)=15 then RT else 0 end) as '15', 
sum(case when substring(tiempo,9,2)=16 then RT else 0 end) as '16', 
sum(case when substring(tiempo,9,2)=17 then RT else 0 end) as '17', 
sum(case when substring(tiempo,9,2)=18 then RT else 0 end) as '18', 
sum(case when substring(tiempo,9,2)=19 then RT else 0 end) as '19', 
sum(case when substring(tiempo,9,2)=20 then RT else 0 end) as '20', 
sum(case when substring(tiempo,9,2)=21 then RT else 0 end) as '21', 
sum(case when substring(tiempo,9,2)=22 then RT else 0 end) as '22', 
sum(case when substring(tiempo,9,2)=23 then RT else 0 end) as '23', 
sum(case when substring(tiempo,9,2)=24 then RT else 0 end) as '24', 
sum(case when substring(tiempo,9,2)=25 then RT else 0 end) as '25', 
sum(case when substring(tiempo,9,2)=26 then RT else 0 end) as '26', 
sum(case when substring(tiempo,9,2)=27 then RT else 0 end) as '27', 
sum(case when substring(tiempo,9,2)=28 then RT else 0 end) as '28', 
sum(case when substring(tiempo,9,2)=29 then RT else 0 end) as '29', 
sum(case when substring(tiempo,9,2)=30 then RT else 0 end) as '30', 
sum(case when substring(tiempo,9,2)=31 then RT else 0 end) as '31' 
from actividad.aralleida_tw 
where substring(tiempo,6,2)=%actual_month% AND substring(tiempo,1,4)=%actual_year%
union 
select CONCAT('RESP'), 
sum(case when substring(tiempo,9,2)=01 then respuestas else 0 end) as '01', 
sum(case when substring(tiempo,9,2)=02 then respuestas else 0 end) as '02', 
sum(case when substring(tiempo,9,2)=03 then respuestas else 0 end) as '03', 
sum(case when substring(tiempo,9,2)=04 then respuestas else 0 end) as '04', 
sum(case when substring(tiempo,9,2)=05 then respuestas else 0 end) as '05', 
sum(case when substring(tiempo,9,2)=06 then respuestas else 0 end) as '06', 
sum(case when substring(tiempo,9,2)=07 then respuestas else 0 end) as '07', 
sum(case when substring(tiempo,9,2)=08 then respuestas else 0 end) as '08', 
sum(case when substring(tiempo,9,2)=09 then respuestas else 0 end) as '09', 
sum(case when substring(tiempo,9,2)=10 then respuestas else 0 end) as '10', 
sum(case when substring(tiempo,9,2)=11 then respuestas else 0 end) as '11', 
sum(case when substring(tiempo,9,2)=12 then respuestas else 0 end) as '12', 
sum(case when substring(tiempo,9,2)=13 then respuestas else 0 end) as '13', 
sum(case when substring(tiempo,9,2)=14 then respuestas else 0 end) as '14', 
sum(case when substring(tiempo,9,2)=15 then respuestas else 0 end) as '15', 
sum(case when substring(tiempo,9,2)=16 then respuestas else 0 end) as '16', 
sum(case when substring(tiempo,9,2)=17 then respuestas else 0 end) as '17', 
sum(case when substring(tiempo,9,2)=18 then respuestas else 0 end) as '18', 
sum(case when substring(tiempo,9,2)=19 then respuestas else 0 end) as '19', 
sum(case when substring(tiempo,9,2)=20 then respuestas else 0 end) as '20', 
sum(case when substring(tiempo,9,2)=21 then respuestas else 0 end) as '21', 
sum(case when substring(tiempo,9,2)=22 then respuestas else 0 end) as '22', 
sum(case when substring(tiempo,9,2)=23 then respuestas else 0 end) as '23', 
sum(case when substring(tiempo,9,2)=24 then respuestas else 0 end) as '24', 
sum(case when substring(tiempo,9,2)=25 then respuestas else 0 end) as '25', 
sum(case when substring(tiempo,9,2)=26 then respuestas else 0 end) as '26', 
sum(case when substring(tiempo,9,2)=27 then respuestas else 0 end) as '27', 
sum(case when substring(tiempo,9,2)=28 then respuestas else 0 end) as '28', 
sum(case when substring(tiempo,9,2)=29 then respuestas else 0 end) as '29', 
sum(case when substring(tiempo,9,2)=30 then respuestas else 0 end) as '30', 
sum(case when substring(tiempo,9,2)=31 then respuestas else 0 end) as '31' 
from actividad.aralleida_tw 
where substring(tiempo,6,2)=%actual_month% AND substring(tiempo,1,4)=%actual_year%
union 
select CONCAT('GUSTA'), 
sum(case when substring(tiempo,9,2)=01 then me_gusta else 0 end) as '01', 
sum(case when substring(tiempo,9,2)=02 then me_gusta else 0 end) as '02', 
sum(case when substring(tiempo,9,2)=03 then me_gusta else 0 end) as '03', 
sum(case when substring(tiempo,9,2)=04 then me_gusta else 0 end) as '04', 
sum(case when substring(tiempo,9,2)=05 then me_gusta else 0 end) as '05', 
sum(case when substring(tiempo,9,2)=06 then me_gusta else 0 end) as '06', 
sum(case when substring(tiempo,9,2)=07 then me_gusta else 0 end) as '07', 
sum(case when substring(tiempo,9,2)=08 then me_gusta else 0 end) as '08', 
sum(case when substring(tiempo,9,2)=09 then me_gusta else 0 end) as '09', 
sum(case when substring(tiempo,9,2)=10 then me_gusta else 0 end) as '10', 
sum(case when substring(tiempo,9,2)=11 then me_gusta else 0 end) as '11', 
sum(case when substring(tiempo,9,2)=12 then me_gusta else 0 end) as '12', 
sum(case when substring(tiempo,9,2)=13 then me_gusta else 0 end) as '13', 
sum(case when substring(tiempo,9,2)=14 then me_gusta else 0 end) as '14', 
sum(case when substring(tiempo,9,2)=15 then me_gusta else 0 end) as '15', 
sum(case when substring(tiempo,9,2)=16 then me_gusta else 0 end) as '16', 
sum(case when substring(tiempo,9,2)=17 then me_gusta else 0 end) as '17', 
sum(case when substring(tiempo,9,2)=18 then me_gusta else 0 end) as '18', 
sum(case when substring(tiempo,9,2)=19 then me_gusta else 0 end) as '19', 
sum(case when substring(tiempo,9,2)=20 then me_gusta else 0 end) as '20', 
sum(case when substring(tiempo,9,2)=21 then me_gusta else 0 end) as '21', 
sum(case when substring(tiempo,9,2)=22 then me_gusta else 0 end) as '22', 
sum(case when substring(tiempo,9,2)=23 then me_gusta else 0 end) as '23', 
sum(case when substring(tiempo,9,2)=24 then me_gusta else 0 end) as '24', 
sum(case when substring(tiempo,9,2)=25 then me_gusta else 0 end) as '25', 
sum(case when substring(tiempo,9,2)=26 then me_gusta else 0 end) as '26', 
sum(case when substring(tiempo,9,2)=27 then me_gusta else 0 end) as '27', 
sum(case when substring(tiempo,9,2)=28 then me_gusta else 0 end) as '28', 
sum(case when substring(tiempo,9,2)=29 then me_gusta else 0 end) as '29', 
sum(case when substring(tiempo,9,2)=30 then me_gusta else 0 end) as '30', 
sum(case when substring(tiempo,9,2)=31 then me_gusta else 0 end) as '31' 
from actividad.aralleida_tw 
where substring(tiempo,6,2)=%actual_month% AND substring(tiempo,1,4)=%actual_year%
union 
select CONCAT('CLICKS'), 
sum(case when substring(tiempo,9,2)=01 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '01', 
sum(case when substring(tiempo,9,2)=02 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '02', 
sum(case when substring(tiempo,9,2)=03 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '03', 
sum(case when substring(tiempo,9,2)=04 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '04', 
sum(case when substring(tiempo,9,2)=05 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '05', 
sum(case when substring(tiempo,9,2)=06 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '06', 
sum(case when substring(tiempo,9,2)=07 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '07', 
sum(case when substring(tiempo,9,2)=08 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '08', 
sum(case when substring(tiempo,9,2)=09 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '09', 
sum(case when substring(tiempo,9,2)=10 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '10', 
sum(case when substring(tiempo,9,2)=11 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '11', 
sum(case when substring(tiempo,9,2)=12 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '12', 
sum(case when substring(tiempo,9,2)=13 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '13', 
sum(case when substring(tiempo,9,2)=14 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '14', 
sum(case when substring(tiempo,9,2)=15 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '15', 
sum(case when substring(tiempo,9,2)=16 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '16', 
sum(case when substring(tiempo,9,2)=17 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '17', 
sum(case when substring(tiempo,9,2)=18 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '18', 
sum(case when substring(tiempo,9,2)=19 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '19', 
sum(case when substring(tiempo,9,2)=20 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '20', 
sum(case when substring(tiempo,9,2)=21 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '21', 
sum(case when substring(tiempo,9,2)=22 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '22', 
sum(case when substring(tiempo,9,2)=23 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '23', 
sum(case when substring(tiempo,9,2)=24 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '24', 
sum(case when substring(tiempo,9,2)=25 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '25', 
sum(case when substring(tiempo,9,2)=26 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '26', 
sum(case when substring(tiempo,9,2)=27 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '27', 
sum(case when substring(tiempo,9,2)=28 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '28', 
sum(case when substring(tiempo,9,2)=29 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '29', 
sum(case when substring(tiempo,9,2)=30 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '30', 
sum(case when substring(tiempo,9,2)=31 then (clics_de_perfil)+(clics_en_url)+(clics_de_etiquetas)+(ampliaciones_de_detalles)+(clics_en_enlaces_permanentes) else 0 end) as '31' 
from actividad.aralleida_tw
where substring(tiempo,6,2)=%actual_month% AND substring(tiempo,1,4)=%actual_year%